services:
  hydrofarm-postgres:
    image: postgres:15
    container_name: hydrofarm-postgres
    environment:
      POSTGRES_USER: hydrofarm_user
      POSTGRES_PASSWORD: hydrofarm_pass
      POSTGRES_DB: hydrofarm
    ports:
      - "5432:5432"

  hydrofarm-mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: hydrofarm-mosquitto
    ports:
      - "1883:1883"

  hydrofarm-backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: hydrofarm-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=hydrofarm-postgres
      - POSTGRES_DB=hydrofarm
      - POSTGRES_USER=hydrofarm_user
      - POSTGRES_PASSWORD=hydrofarm_pass
      - PYTHONPATH=/app/backend
    depends_on:
      - hydrofarm-postgres

  hydrofarm-agent:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: hydrofarm-agent
    restart: always
    environment:
      - API_URL=http://hydrofarm-backend:8000
      - PYTHONPATH=/app/backend
    command: python backend/devices/rpi_agent.py
    depends_on:
      - hydrofarm-backend